### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Shunsuke-1994** [davidhoksza/traveler#12]
Hi! 
I met an install error. 
I ran this command:
```
git clone https://github.com/davidhoksza/traveler
cd traveler/src
make build
```
and, the error is: 
```
****************MAKEFILE-GENERATING:tree****************

make --directory=tree --makefile=Makefile make
make[1]: *** No rule to make target `../build//rna_tree_label.cpp.mk', needed by `make'.  Stop.
make: *** [tree] Error 2
```
I am using the following env: 
OS: macOS High Sierra 10.13.6
gcc (GCC): 4.8.5
GNU Make: 3.81

I couldn't understand why this error happened. Is the problem in my env?
I would appreciate if you know how to solve this. 

Best regards, 
Shunsuke

**Comment by davidhoksza** [comment]
To be honest, I tested it on Ubuntu only. Not with macOS. But a bulletproof solution is using the docker image (see the main README). Would that be a solution for you?

**Comment by Shunsuke-1994** [comment]
Thank you for your reply. 

I briefly tried to install on Google Colab(Ubuntu) and I could installed traveler without any errors. 
Probably my env problem. I will use traveler on Ubuntu. 
Thank you.
