### ISSUE TITLE
Using CRW bpseq files instead of template fasta

### ISSUE THREAD

**Issue by AntonPetrov** [davidhoksza/traveler#4]
Thanks again for the great software!

One of the required inputs is a FASTA file with the sequence and structure of the template. It wasn't immediately clear to me how to get these files in a (semi)automatic way, so I ended up downloading the CRW structures in `bpseq` format and then converting bpseq to FASTA using the [RNApdbee](http://rnapdbee.cs.put.poznan.pl/) web service. 

I have 2 questions:

1. Is there a better way to get the template FASTA files?
2. Could Traveler take the bpseq files as an input to avoid the conversion process?

Thank you for looking into this!

**Comment by davidhoksza** [comment]
We used only a few templates so we did that manually. But you are right, that such functionality might be useful when you need to automate the process. 

As a quick solution, I implemented a small python script which can be found in the utility directory. It takes a bpseq file on input and outputs a FASTA file which can be passed to Traveler. I tested on the mouse bpseq (non-pseudoknotted) file downloaded from CRW that it generates the same structure which can be found in the data directory (mouse.fasta).

Is such a solution sufficient for your use case?

**Comment by AntonPetrov** [comment]
The new script is great, thank you David! Just what I needed.

I may raise more issues as I continue playing around with Traveler. So far it works really well!

**Comment by davidhoksza** [comment]
Sure, no problem :)
